api_get_tasks:
  path: /api/todo
  controller: App\Infrastructure\EntryPoint\Api\GetTasksController
  methods: ['GET']

api_add_task:
  path: /api/todo
  controller: App\Infrastructure\EntryPoint\Api\AddTaskController
  methods: ['POST']

api_mark_task:
  path: /api/todo/{taskId}
  controller: App\Infrastructure\EntryPoint\Api\MarkTaskController
  methods: ['PATCH']
